### ISSUE TITLE
Use service get_forecasts for forecasts

### ISSUE THREAD

**Issue by Ayuus** [jaydeethree/Home-Assistant-weatherdotcom#19]
Hello,

Since I updated HA to 2023.12, I get the following message:

> Detected use of deprecated service `weather.get_forecast`
> Use weather.get_forecasts instead which supports multiple entities.
> 
> Please replace this service and adjust your automations and scripts and select submit to close this issue.

Woul it be possible to adapt his integration to use the new HA service?

Regards, Ronald

**Comment by Ayuus** [comment]
For everyone who struggles with weather.get_forcasts as I did,
this is what is workin for me:
```
template: 
    # daily forcast data, trigger sensor is necessary for new HA
  - trigger:
    - platform: state
      entity_id: weather.home
    action:
      service: weather.get_forecasts
      target:
        entity_id: weather.home        
      data:
        type: daily
      response_variable: daily
    sensor:
      - name: "Daily Weather Forecast"
        unique_id: daily_weather_forecast
        state: "{{ now().isoformat() }}"
        attributes:
          forecast: "{{ daily['weather.home'].forecast}}"
 
    # hourly forcast data, trigger sensor is necessary for new HA
  - trigger:
    - platform: time_pattern
      hours: /1
    action:
      service: weather.get_forecasts
      target:
        entity_id: weather.home        
      data:
        type: hourly
      response_variable: hourly
    sensor:
      - name: "Hourly Weather Forecast"
        unique_id: hourly_weather_forecast
        state: "{{ now().isoformat() }}"
        attributes:
          forecast: "{{ hourly['weather.home'].forecast}}"
```
